[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = {CLAUDE_API_KEY = ""}

[headers]
  for = "/"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
